"""Smoke tests for package imports."""

import importlib

MODULES = [
    "domain",
    "domain.entities.user",
    "domain.entities.session",
    "domain.entities.role",
    "domain.value_objects.plain_password",
    "domain.services.auth",
    "domain.services.coaching_access",
    "domain.services.authorization",
    "application.security.coaching_access_guard",
    "domain.repositories.user_repository",
    "domain.repositories.session_repository",
    "application.use_cases.register_user",
    "application.use_cases.login_user",
    "application.use_cases.logout_user",
    "application.use_cases.get_current_user",
    "application.use_cases.list_users",
    "application.use_cases.authenticate_session",
    "application.security.authorization_guard",
    "application.dto.user_queries",
    "domain.value_objects.pagination",
    "infrastructure.logging.setup",
    "infrastructure.db.models",
    "infrastructure.db.repositories",
    "infrastructure.db.seed_admin",
    "infrastructure.db.engine",
    "infrastructure.security.scrypt_password_hasher",
    "infrastructure.security.sha256_session_token",
    "interfaces.http",
    "domain.entities.invitation",
    "domain.entities.coach_athlete_link",
    "domain.entities.athlete_profile",
    "domain.entities.personal_record",
    "domain.entities.workout_feedback",
    "domain.entities.invitation_status",
    "domain.entities.record_type",
    "domain.entities.gender",
    "domain.value_objects.invitation_id",
    "domain.value_objects.coach_athlete_link_id",
    "domain.value_objects.personal_record_id",
    "domain.value_objects.workout_feedback_id",
    "domain.value_objects.height_cm",
    "domain.value_objects.weight_kg",
    "domain.value_objects.age",
    "domain.value_objects.garmin_report_url",
    "domain.value_objects.record_value",
    "domain.value_objects.record_unit",
    "domain.value_objects.feedback_text",
    "domain.value_objects.record_name",
    "domain.repositories.invitation_repository",
    "domain.repositories.coach_athlete_link_repository",
    "domain.repositories.athlete_profile_repository",
    "domain.repositories.personal_record_repository",
    "domain.repositories.workout_feedback_repository",
    "application.dto.coaching",
    "application.use_cases.send_invitation",
    "application.use_cases.accept_invitation",
    "application.use_cases.decline_invitation",
    "application.use_cases.save_athlete_profile",
    "application.use_cases.personal_record_commands",
    "application.use_cases.submit_workout_feedback",
    "application.use_cases.list_coaching_data",
    "interfaces.http.routes.coaching",
    "infrastructure.db.coaching_repositories",
]


def test_all_modules_import_cleanly() -> None:
    for module_name in MODULES:
        importlib.import_module(module_name)
